/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufes.pss.prova2.view;

import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author dener
 */
public class ViewUltimasImagens extends javax.swing.JFrame {

    /**
     * Creates new form ViewUltimasImagens
     */
    public ViewUltimasImagens() {
        initComponents();
        setLocationRelativeTo(getParent());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        imagemHD = new javax.swing.JLabel();
        txtInformacoes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelScroll = new javax.swing.JPanel();
        miniaturaPanel1 = new javax.swing.JPanel();
        miniatura1 = new javax.swing.JLabel();
        miniaturaPanel2 = new javax.swing.JPanel();
        miniatura2 = new javax.swing.JLabel();
        miniaturaPanel3 = new javax.swing.JPanel();
        miniatura3 = new javax.swing.JLabel();
        miniaturaPanel4 = new javax.swing.JPanel();
        miniatura4 = new javax.swing.JLabel();
        miniaturaPanel5 = new javax.swing.JPanel();
        miniatura5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VISUALIZAR ÚLTIMAS IMAGENS");
        setBackground(new java.awt.Color(23, 23, 23));
        setResizable(false);

        panelPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        imagemHD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagemHD, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagemHD, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        txtInformacoes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtInformacoes.setText("Clique na miniatura para exibir a imagem em alta resolução.");

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        panelScroll.setBackground(new java.awt.Color(255, 255, 255));

        miniatura1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout miniaturaPanel1Layout = new javax.swing.GroupLayout(miniaturaPanel1);
        miniaturaPanel1.setLayout(miniaturaPanel1Layout);
        miniaturaPanel1Layout.setHorizontalGroup(
            miniaturaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(miniaturaPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(miniatura1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        miniaturaPanel1Layout.setVerticalGroup(
            miniaturaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(miniaturaPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(miniatura1, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addContainerGap())
        );

        miniatura2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout miniaturaPanel2Layout = new javax.swing.GroupLayout(miniaturaPanel2);
        miniaturaPanel2.setLayout(miniaturaPanel2Layout);
        miniaturaPanel2Layout.setHorizontalGroup(
            miniaturaPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(miniaturaPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(miniatura2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        miniaturaPanel2Layout.setVerticalGroup(
            miniaturaPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(miniaturaPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(miniatura2, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addContainerGap())
        );

        miniatura3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout miniaturaPanel3Layout = new javax.swing.GroupLayout(miniaturaPanel3);
        miniaturaPanel3.setLayout(miniaturaPanel3Layout);
        miniaturaPanel3Layout.setHorizontalGroup(
            miniaturaPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(miniaturaPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(miniatura3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        miniaturaPanel3Layout.setVerticalGroup(
            miniaturaPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(miniaturaPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(miniatura3, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addContainerGap())
        );

        miniatura4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout miniaturaPanel4Layout = new javax.swing.GroupLayout(miniaturaPanel4);
        miniaturaPanel4.setLayout(miniaturaPanel4Layout);
        miniaturaPanel4Layout.setHorizontalGroup(
            miniaturaPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(miniaturaPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(miniatura4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        miniaturaPanel4Layout.setVerticalGroup(
            miniaturaPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(miniaturaPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(miniatura4, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addContainerGap())
        );

        miniatura5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout miniaturaPanel5Layout = new javax.swing.GroupLayout(miniaturaPanel5);
        miniaturaPanel5.setLayout(miniaturaPanel5Layout);
        miniaturaPanel5Layout.setHorizontalGroup(
            miniaturaPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
            .addGroup(miniaturaPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(miniaturaPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(miniatura5, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        miniaturaPanel5Layout.setVerticalGroup(
            miniaturaPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
            .addGroup(miniaturaPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(miniaturaPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(miniatura5, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout panelScrollLayout = new javax.swing.GroupLayout(panelScroll);
        panelScroll.setLayout(panelScrollLayout);
        panelScrollLayout.setHorizontalGroup(
            panelScrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelScrollLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panelScrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(miniaturaPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(miniaturaPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(miniaturaPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(miniaturaPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(miniaturaPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        panelScrollLayout.setVerticalGroup(
            panelScrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelScrollLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(miniaturaPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(miniaturaPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(miniaturaPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(miniaturaPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(miniaturaPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        jScrollPane1.setViewportView(panelScroll);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtInformacoes)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtInformacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getImagemHD() {
        return imagemHD;
    }

    public JLabel getMiniatura1() {
        return miniatura1;
    }

    public JLabel getMiniatura2() {
        return miniatura2;
    }

    public JLabel getMiniatura3() {
        return miniatura3;
    }

    public JLabel getMiniatura4() {
        return miniatura4;
    }

    public JLabel getMiniatura5() {
        return miniatura5;
    }

    public JPanel getMiniaturaPanel1() {
        return miniaturaPanel1;
    }

    public JPanel getMiniaturaPanel2() {
        return miniaturaPanel2;
    }

    public JPanel getMiniaturaPanel3() {
        return miniaturaPanel3;
    }

    public JPanel getMiniaturaPanel4() {
        return miniaturaPanel4;
    }

    public JPanel getMiniaturaPanel5() {
        return miniaturaPanel5;
    }

    public JPanel getPanelPrincipal() {
        return panelPrincipal;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imagemHD;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel miniatura1;
    private javax.swing.JLabel miniatura2;
    private javax.swing.JLabel miniatura3;
    private javax.swing.JLabel miniatura4;
    private javax.swing.JLabel miniatura5;
    private javax.swing.JPanel miniaturaPanel1;
    private javax.swing.JPanel miniaturaPanel2;
    private javax.swing.JPanel miniaturaPanel3;
    private javax.swing.JPanel miniaturaPanel4;
    private javax.swing.JPanel miniaturaPanel5;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelScroll;
    private javax.swing.JLabel txtInformacoes;
    // End of variables declaration//GEN-END:variables
}
